# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 13780fc1e98359e7b2ef499680cd9ef6ac17218ef006f0ee31de4da4c836329f9473203f2e1261393282a42bb4ee35352856d10efca63b65c3073b6f594f50d5

test:
  secret_key_base: 33a232dd98662eaf7d364706f9e6d561b0ebb618e2b9b84b4c3212ae6b4501ef3043345d2ab48592557cab407e7b29181e29b31e1cbf586931ea7b7c33d0ba01

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
